from datetime import date
import file_writer


def create_list_xml(filename, ctaq):
	# create file: metadata/list.xml 

	fw = file_writer.FileWriter(filename)

	today = str(date.today())
	s = """<?xml version="1.0" encoding="UTF-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="list.xsd" schemaMajorVersion="1">
	<revisions>
		<revision date=\"""" + today + """\">Automatically generated by configPrep. Manual verification is needed.</revision>
	</revisions>
	<comment>
This is the main configuration file for deployment. It
describes the objects that need some action during deployment or later removal,
e.g. to enable setting the permission or uploading the files. Use the following elements:
- For CSV based packages: SCHEMA, TABLE, BFILES
- For SIARD based packages: SCHEMA
- For additional VIEW or TABLE elements created by createdb01.sql: VIEW
	</comment>
	<schemas>"""
	fw.print(s)

	for s in ctaq.all_schemas:
		fw.print("\t\t<schema>" + s + "</schema>")

	s = """\t</schemas>
	<views>
		<view></view>
	</views>"""

	fw.print(s)
	fw.print("\t<tables>")
	fw.print("\t\t<!-- Double quotes for table names will be added automatically. -->")
	fw.print("\t\t<!-- Check the header attribute value. -->")
	for csv, table in ctaq.all_tables_and_csv_files.items():
		if csv:
			fw.print("\t\t<table file=\"" + csv + "\" header=\"0\" delimiter=\"tab\">" + table + "</table>")
	fw.print("\t</tables>")

	s = """\t<bfiles>
		<bfile></bfile>
	</bfiles>
</configuration>
"""
	fw.print(s)
	fw.close()
